//
// Created by jesse on 11/5/2021.
//

#include "Student.h"


Student::Student(string setSubject,
                 string setSchool,
                 char setSex,
                 int setAge,
                 char setAddress,
                 string setFamsize,
                 char setPstatus,
                 int setMedu,
                 int setFedu,
                 string setMjob,
                 string setFjob,
                 string setReason,
                 string setGuardian,
                 int setTraveltime,
                 int setStudytime,
                 int setFailures,
                 bool setSchoolsup,
                 bool setFamsup,
                 bool setPaid,
                 bool setActivities,
                 bool setNursery,
                 bool setHigher,
                 bool setInternet,
                 bool setRomantic,
                 int setFamrel,
                 int setFreetime,
                 int setGoout,
                 int setDalc,
                 int setWalc,
                 int setHealth,
                 int setAbsences,
                 int setG1,
                 int setG2,
                 int setG3)
        :
        subject(std::move(setSubject)),
        school(std::move(setSchool)),
        sex(setSex),
        age(setAge),
        address(setAddress),
        famsize(std::move(setFamsize)),
        Pstatus(setPstatus),
        Medu(setMedu),
        Fedu(setFedu),
        Mjob(std::move(setMjob)),
        Fjob(std::move(setFjob)),
        reason(std::move(setReason)),
        guardian(std::move(setGuardian)),
        traveltime(setTraveltime),
        studytime(setStudytime),
        failures(setFailures),
        schoolsup(setSchoolsup),
        famsup(setFamsup),
        paid(setPaid),
        activities(setActivities),
        nursery(setNursery),
        higher(setHigher),
        internet(setInternet),
        romantic(setRomantic),
        famrel(setFamrel),
        freetime(setFreetime),
        goout(setGoout),
        Dalc(setDalc),
        Walc(setWalc),
        health(setHealth),
        absences(setAbsences),
        G1(setG1),
        G2(setG2),
        G3(setG3) {

}

